### ISSUE TITLE
BDF Loader

### ISSUE THREAD

**Issue by kevinjos** [breuderink/eegtools#11]
What outstanding work is left on the bdf-loader branch required before merging into master?

**Comment by breuderink** [comment]
I haven't extensively unit-tested it, and I am not sure all of the BDF format is supported. I would like to review my code before merging it back. But it should be usable in it's current form. You can use the unmarked branch if you need to import BDF files.

**Comment by kevinjos** [comment]
Sounds good. I have started using it to unmarshal BDF files I am writing in Go from the 24bit OpenBCI EEG. It would enchance interoperability to have an BDF/EDF reader in PyPi. Let me know if there's anything I can do to help.

**Comment by breuderink** [comment]
If you could check the BDF implementation that would be really helpful :).
