### ISSUE TITLE
16-bit resolution

### ISSUE THREAD

**Issue by miggot** [breuderink/eegtools#12]
Hi, 
should data be read in 16-bit format instead of something else? Original EDF signals is stored in 16 bit resolution so no loss of data happens then.

Changing lines 130-134 in edfplus.py as follows seems to be more memory efficient

```
  else:
    #2-byte little-endian integers
    dig = np.fromstring(samples, '<i2').astype(float)
    phys = (dig - dig_min[i]) * gain[i] + phys_min[i]
    signals.append(phys.astype(np.float16))
```

**Comment by breuderink** [comment]
I think you are right. I tend to work with 32 bits or 64 bits floats for signal processing accuracy, so I won't benefit much from this gain in efficiency. But if you make I pull request I would be happy to merge it.
