### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by shihray** [breuderink/eegtools#15]
hello! I have some problem with this function
now I got an array the shape is (15, 3) that 3 is electrode point (c3,c4,cz)
and 15 is the data in one electrode point
how should I put this array to CSP function

**Comment by breuderink** [comment]
The CSP function expects covariance matrices, which would be a 3 by 3 matrix in your case. See https://github.com/breuderink/eegtools/blob/master/examples/ex_csp_motor_imagery.py#L48 for example usage.
