### ISSUE TITLE
ModuleNotFoundError: No module named 'data'

### ISSUE THREAD

**Issue by vivek9746** [breuderink/eegtools#17]
I installed eegtools using pip install eegtools --user
when in run the command :
**>>>import eegtools**
this is the error:

_ModuleNotFoundError: No module named 'data_

does anybody know how to fix this?

**Comment by breuderink** [comment]
Hmm, it now does the same on my system, although the code was not changed. Perhaps it is a Python 3 issue?

**Comment by breuderink** [comment]
I tried to convert with `2to3`, which solves the import issues. Now the unit tests fail, in ways that they should not :(. Perhaps you best bet is to try Python 2.

**Comment by rahimrasool** [comment]
I am facing a similar issue but in my case it isnt detecting featex

**Comment by breuderink** [comment]
Unfortunately I cannot support Python 3 right now. I welcome pull-request though.

**Comment by lidh15** [comment]
But we all know that Python 2 is going to an end...

**Comment by Jyotishko** [comment]
Do we have a resolution to the above query? 

I also face the same error:
ModuleNotFoundError: No module named 'data'
