### ISSUE TITLE
ImportError: No module named 'data'

### ISSUE THREAD

**Issue by Irving-ren** [breuderink/eegtools#20]
Hi, the error occurred when trying the example of this eegtools package. Could you give any advise to solve it? 
![screenshot from 2018-08-15 17-43-39](https://user-images.githubusercontent.com/13758812/44139701-cf12d0d8-a0b2-11e8-93d2-367cd93c3c69.png)

**Comment by Avcu** [comment]
Hate people who don't wanna waste their precious time to check old issues
https://github.com/breuderink/eegtools/issues/17

**Comment by Irving-ren** [comment]
Thanks for your reply.
