### ISSUE TITLE
ModuleNotFoundError: No module named 'featex'

### ISSUE THREAD

**Issue by QiuShanZhao** [breuderink/eegtools#23]
When I try to import eegtools,it turns out that"ModuleNotFoundError: No module named 'featex'",but featex.py is exactly where it is. It's strange, why?

**Comment by breuderink** [comment]
I don't know. Are you using Python 3? Eegtools used to work fine with Python 2, but requires non-trivial work to update it to Python 3.

**Comment by QiuShanZhao** [comment]
> 2, but requires non-trivial work to update it to Python 3.

Thanks, It is exactly the python version problem, and I have solved the problem by using Python 2.
