### ISSUE TITLE
Problem loading data on "data.bcicomp3_4a.load" in Windows

### ISSUE THREAD

**Issue by leonpalafox** [breuderink/eegtools#7]
In Windows 7, when you run out of the box:

```
d=eegtools.data.bcicomp3_4a.load('aa')
```

You get :

```
zlib.error:Error -3 while decompressing: invalid distance too far back
```

I'm trying to figure out where it is happening, I had a similar issue once, and it was related with windows needing to load the data as binaries.

Best

**Comment by GitHubxiuwen** [comment]
@ssakhavi  I used your code in the bcicomp3_4a.py file on the Windows machine.But there is already  the Error -3 while decompressing: invalid distance too far back.
I'm not sure the location of the modification is right.
def load_mat(mat_train, mat_test, rec_id):
  '''Load BCI Comp. 3.4a specific Matlab files.'''
  subject = 'aa'
  rec_id = 'bcicomp3.4a-%s' % subject
  mat_train = r'C:\Users\User\eegtools_data\bbci.de\competition\download\competition_iii\berlin\100Hz\data_set_IVa_aa_mat\100 Hz\data_set_IVa_aa.mat'
  mat_test = r'C:\Users\User\eegtools_data\bbci.de\competition\download\competition_iii\berlin\100Hz\data_set_IVa_aa_mat\true_labels_aa.mat '
  mat = io.loadmat(mat_train, struct_as_record=True)
  mat_true = io.loadmat(mat_test, struct_as_record=True)
Please check it.
Best

**Comment by Irving-ren** [comment]
Hi, 
I'm working with Anaconda on Ubuntu python 2.7 and it occurred the same problem.
![screenshot from 2018-08-20 11-07-37](https://user-images.githubusercontent.com/13758812/44316914-4ae76480-a469-11e8-81e2-efa2a551f0ff.png)

However, that discussion have closed. And, I tried the solution that mentioned by @ssakhavi . Unfortunately, the decompressed file seems like uncompleted. The existed file didn't include true_labels_aa.mat file. 
![screenshot from 2018-08-20 11-18-45](https://user-images.githubusercontent.com/13758812/44317191-d7deed80-a46a-11e8-8b4f-9bfa89044e6c.png)

Do you have a clue for this problem?
Best
Irving

**Comment by breuderink** [comment]
The true labels have to be downloaded separately from http://www.bbci.de/competition/iii/results/index.html#labels. See also this line in the loader: https://github.com/breuderink/eegtools/blob/master/eegtools/data/bcicomp3_4a.py#L82.

**Comment by GitHubxiuwen** [comment]
Thanks for your reply.I found it in the link you sent！

**Comment by breuderink** [comment]
Closing this discussion, as underlying issue is reported in #19 .
