### ISSUE TITLE
Code licensing is difficult to find

### ISSUE THREAD

**Issue by griffinmilsap** [breuderink/eegtools#9]
Hey Boris,

It's a bit difficult to find a license associated with this code.  According to your setup.py I can see that it's currently BSD licensed (I assume four-clause?) but you never really specified what code-use terms you specify.  All source files, however, are missing in-source license statements instead indicating that the code is simply copyrighted to you.  This leads me to believe that the code is not actually licensed under an open source license and isn't free for use, so I'm wary to actually use it.

Could you specify/clarify with a LICENSE.txt or some in-source license information?

**Comment by breuderink** [comment]
It is licensed under a 3-clause BSD license. Is should indeed add a LICENSE.txt. I don't intend to add the license to each file — that feels like visual noise to me.

Could you perhaps make a pull request for a 3-clause BSD license? Than I'll happily merge it :).

**Comment by griffinmilsap** [comment]
#10 Done and done :)

**Comment by breuderink** [comment]
Thanks, merged in #10.
